services:
  postgres:
    container_name: postgres
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: vdele_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "!Qq12345"
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: