services:
  postgres:
    container_name: postgres
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: vdele_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "!Qq12345"
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  seq:
    container_name: seq
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    ports:
      - "8081:80"
      - "5341:5341"
    restart: always
    volumes:
      - seq_data:/data

volumes:
  postgres_data:
  seq_data: